services:
  dnsmasq-proxydhcp:
    image: andyattebery/dnsmasq-proxydhcp:latest
    build:
      context: .
    container_name: dnsmasq-proxydhcp
    cap_add:
      - NET_ADMIN
    environment:
      - DNSMASQ_PROXY_SUBNET=192.168.1.1
      - NETBOOTXYZ_SERVER_IP=192.168.1.235
    network_mode: host
    # ports:
    #   - 67:67/udp
      # - 68:68/tcp
      # - 68:68/udp
